name: Docker Image CI

on:
  push:
    branches: [ "adding-readme" ]
  pull_request:
    branches: [ "adding-readme" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose build